services:
  # Main Backend API Service
  - type: web
    name: easyflow-backend
    runtime: node
    env: node
    region: oregon
    plan: starter # paid tier to keep backend always-on
    buildCommand: cd rpa-system \
      && npm install --production \
      && echo "Installing automation python deps" \
      && cd automation && pip install -r requirements.txt --no-cache-dir || true
    startCommand: cd rpa-system && node backend/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3030
      - key: ENABLE_EMAIL_WORKER
        value: "true"
      - key: SUPABASE_URL
        fromDatabase:
          name: easyflow-postgres
          property: connectionString
      - key: SUPABASE_SERVICE_ROLE
        sync: false # Set manually in Render dashboard
      - key: SUPABASE_ANON_KEY
        sync: false # Set manually in Render dashboard
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_PATH
        value: /opt/render/project/src/rpa-system/backend/config/firebase-service-account.json
      - key: API_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://easyflow-dashboard.vercel.app,https://app.easyflow.com

# Database (if using Render's Postgres)
databases:
  - name: easyflow-postgres
    databaseName: easyflow_production
    region: oregon

  # Redis for caching (optional)
  - name: easyflow-redis
    region: oregon
    plan: free
