services:
  # Backend API Service
  - type: web
    name: easyflow-backend
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables from .env.render here
    
  # Frontend Service (if deploying separately)
  # - type: web
  #   name: easyflow-frontend
  #   runtime: static
  #   plan: starter
  #   buildCommand: npm run build
  #   staticPublishPath: ./build
  #   routes:
  #     - type: rewrite
  #       source: /*
  #       destination: /index.html