name: Create Backend .env from Secrets

on:
  workflow_dispatch:

jobs:
  create-backend-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create backend .env file from secrets
        run: |
          mkdir -p rpa-system/backend
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> rpa-system/backend/.env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> rpa-system/backend/.env
          echo "KAFKA_BROKERS=${{ secrets.KAFKA_BROKERS }}" >> rpa-system/backend/.env
          echo "AUTOMATION_URL=${{ secrets.AUTOMATION_URL }}" >> rpa-system/backend/.env
          echo "ALLOW_DRAFT_EXECUTION=true" >> rpa-system/backend/.env
