name: Deploy to Render (example)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Render CLI
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          if [ -z "$RENDER_API_KEY" ]; then
            echo "RENDER_API_KEY not set. Set it in repo secrets."; exit 1
          fi
          # Install render CLI using their install script
          curl -s https://cdn.render.com/cli/install.sh | bash

      - name: Authenticate Render CLI
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          ~/.render/bin/render login --api-key "$RENDER_API_KEY"

      - name: Deploy with Render CLI
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          # If you want to deploy a specific service, pass the service id. Otherwise
          # the CLI will use settings from your Render account.
          if [ -n "$RENDER_SERVICE_ID" ]; then
            ~/.render/bin/render services create-deploy --service-id "$RENDER_SERVICE_ID" || ~/.render/bin/render services create-deploy --service-id "$RENDER_SERVICE_ID"
          else
            # Deploy using the Manifest in the repo (if supported by your account)
            ~/.render/bin/render deploy || true
          fi

      - name: Note
        run: |
          echo "This workflow uses the Render CLI. Keep your `render.yaml` in the repo; Render will read it when performing deployments."
