name: Enqueue Welcome Emails

on:
  schedule:
    - cron: "0 8 * * *" # daily at 08:00 UTC

jobs:
  enqueue:
    runs-on: ubuntu-latest
    steps:
      - name: Call enqueue-welcome endpoint
        env:
          APP_URL: ${{ secrets.APP_URL }}
          ADMIN_API_SECRET: ${{ secrets.ADMIN_API_SECRET }}
        run: |
          curl -sS -X POST "$APP_URL/admin/enqueue-welcome" -H "Content-Type: application/json" -H "x-admin-secret: $ADMIN_API_SECRET" -d '{"days":1}' || true
